# Generated by Django 5.2.17 on 2026-08-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_finalize_publishing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Comments stay hidden until you approve them.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="focal_point",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("top", "Top (trim the bottom)"),
                    ("bottom", "Bottom (trim the top)"),
                    ("left", "Left (trim the right)"),
                    ("right", "Right (trim the left)"),
                ],
                default="center",
                help_text="Which part of the picture to keep when it has to be cropped.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "focal_point",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("top", "Top (trim the bottom)"),
                            ("bottom", "Bottom (trim the top)"),
                            ("left", "Left (trim the right)"),
                            ("right", "Right (trim the left)"),
                        ],
                        default="center",
                        max_length=10,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
