# Generated by Django 5.2.17 on 2026-08-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_approve_existing_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="focal_point",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("top", "Top (trim the bottom)"),
                    ("bottom", "Bottom (trim the top)"),
                    ("left", "Left (trim the right)"),
                    ("right", "Right (trim the left)"),
                ],
                default="top",
                help_text="Which part of the picture to keep when it has to be cropped.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="focal_point",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("top", "Top (trim the bottom)"),
                    ("bottom", "Bottom (trim the top)"),
                    ("left", "Left (trim the right)"),
                    ("right", "Right (trim the left)"),
                ],
                default="top",
                max_length=10,
            ),
        ),
    ]
