# Generated by Django 5.2.17 on 2026-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_existing_pictures_keep_their_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="focal_point",
            field=models.CharField(
                choices=[
                    ("center", "Centre — trim every side evenly"),
                    ("top", "Keep the top — trim the sides and the bottom"),
                    ("bottom", "Keep the bottom — trim the sides and the top"),
                    ("left", "Keep the left — trim the right, top and bottom"),
                    ("right", "Keep the right — trim the left, top and bottom"),
                ],
                default="top",
                help_text="Pictures are scaled up or down to fill their box; whatever overflows is trimmed. This picks the edge that must never be trimmed — the trimming comes off the other sides.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="focal_point",
            field=models.CharField(
                choices=[
                    ("center", "Centre — trim every side evenly"),
                    ("top", "Keep the top — trim the sides and the bottom"),
                    ("bottom", "Keep the bottom — trim the sides and the top"),
                    ("left", "Keep the left — trim the right, top and bottom"),
                    ("right", "Keep the right — trim the left, top and bottom"),
                ],
                default="top",
                max_length=10,
            ),
        ),
    ]
