# Generated by Django 5.2.17 on 2026-08-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_clarify_focal_point_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="posts",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="gallery",
                width_field="image_width",
            ),
        ),
    ]
