# Generated by Django 5.2.17 on 2026-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_backfill_image_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                max_length=500,
                null=True,
                upload_to="posts",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                max_length=500,
                upload_to="gallery",
                width_field="image_width",
            ),
        ),
    ]
